2025-04-02 10:52:48,001 - DEBUG - üîß Este es un mensaje de prueba DEBUG - [logger.py:34]
2025-04-02 10:52:48,003 - INFO - ‚Ñπ Este es un mensaje de prueba INFO - [logger.py:35]
2025-04-02 10:52:48,003 - ERROR - ‚ùå Este es un mensaje de prueba ERROR - [logger.py:36]
2025-04-02 10:54:36,733 - DEBUG - üîß Este es un mensaje de prueba DEBUG - [logger.py:34]
2025-04-02 10:54:36,733 - INFO - ‚Ñπ Este es un mensaje de prueba INFO - [logger.py:35]
2025-04-02 10:54:36,733 - ERROR - ‚ùå Este es un mensaje de prueba ERROR - [logger.py:36]
2025-04-02 10:54:37,085 - INFO - üöÄ Aplicaci√≥n iniciada - [main.py:6]
2025-04-02 10:56:05,284 - DEBUG - üîß Este es un mensaje de prueba DEBUG - [logger.py:34]
2025-04-02 10:56:05,285 - INFO - ‚Ñπ Este es un mensaje de prueba INFO - [logger.py:35]
2025-04-02 10:56:05,286 - ERROR - ‚ùå Este es un mensaje de prueba ERROR - [logger.py:36]
2025-04-02 10:56:05,684 - INFO - üöÄ Aplicaci√≥n iniciada - [reporteData.py:11]
2025-04-04 12:59:10,301 - ERROR - 'ZKServices' object has no attribute 'zk' - ZKServices.py:80
2025-04-04 13:03:00,901 - ERROR - 'str' object cannot be interpreted as an integer - ZKServices.py:80
2025-04-04 13:03:13,135 - ERROR - 'str' object cannot be interpreted as an integer - ZKServices.py:80
2025-04-04 13:22:49,700 - ERROR - Cant Enroll user #3 [9] - ZKServices.py:77
2025-04-04 13:22:51,216 - ERROR - Cant Enroll user #2 [9] - ZKServices.py:106
2025-04-04 13:26:35,298 - ERROR - Cant Enroll user #3 [9] - ZKServices.py:106
2025-04-04 13:26:59,582 - ERROR - Cant Enroll user #3 [9] - ZKServices.py:106
2025-04-04 13:32:55,045 - ERROR - Cant Enroll user #3 [9] - ZKServices.py:106
